### ISSUE TITLE
Unable to change password

### ISSUE THREAD

**Issue by sumikasan** [theodi/ODMAT#101]
1. Go to 'Login'
2. Click 'Forgot your password?' link to generate email
3. Click 'Change my password' link
4. Enter the new password into the "New password" and "Confirm new password" fields and click 'Change my password' button

Observation:
"1 errors prohibited this user from being saved - name can't be blank"
![screen shot 2015-03-24 at 11 37 30](https://cloud.githubusercontent.com/assets/7251962/6800837/3ece6da8-d21a-11e4-8cef-68ea776ef3d6.png)

**Comment by ldodds** [comment]
This is same issue as with #102. Your account is currently invalid as there's no name (side effect of you registering against earlier code).

Can you add a name and retest?
