### ISSUE TITLE
Unable to update the password from "My account"

### ISSUE THREAD

**Issue by sumikasan** [theodi/ODMAT#102]
1. Click 'Account'
2. From 'Edit user' enter:
- Password (leave blank if you don't want to change it)
- Password confirmation
- Current password (we need your current password to confirm your changes)
3. Click 'Update'

Observation:
Unable to save the new password - user sees:
"1 error prohibited this user from being saved: Name can't be blank"

![error_password](https://cloud.githubusercontent.com/assets/7251962/6800904/ed14885c-d21a-11e4-8636-79a3df15ec20.png)

**Comment by ldodds** [comment]
I think this is because your account is currently invalid, because you registered before we added a required name. Can you add a name, then try updating?
