### ISSUE TITLE
Error message - Register page

### ISSUE THREAD

**Issue by sumikasan** [theodi/ODMAT#104]
Error messages need to be more user friendly:

- [x] Email is invalid -> Please enter a valid email address

- [ ] Change the message at the top which current reads:
" x errors prohibited this user from being saved"
This should say:
"Oops - please try again"

**Comment by ldodds** [comment]
Revised message for email in client side validation

**Comment by ldodds** [comment]
I've revised this to use add the "Oops..." text. This is only disabled if the user manages to submit an invalid form after bypassing the javascript (or if it failed to load).

To test this you should temporarily disable javascript, or I can demo it.
