### ISSUE TITLE
Password reset email message

### ISSUE THREAD

**Issue by sumikasan** [theodi/ODMAT#105]
The message should say:

Subject: Open Data Pathway: password reset instruction
Hello [Name],

We received the request to reset your password for your account for Open Data Pathway.
Click the link below to reset your password:

Reset my password now

If you have not requested the password reset then don't worry - you can ignore this email. Alternatively you can contact XXX@theodi.org.

**Comment by digitalWestie** [comment]
Which email shall I use for the message?

**Comment by ldodds** [comment]
@rory the email is maturity@theodi.org.

**Comment by digitalWestie** [comment]
cheers
