### ISSUE TITLE
Tidy up the Sign in page

### ISSUE THREAD

**Issue by sumikasan** [theodi/ODMAT#108]
- [x] Email
- [x] Password
- [x] Keep me signed in
- [x] Forgot your password?
- [x] Sign in (button)
- [x] Register now?

Mock-up here:

![screen shot 2015-03-24 at 16 57 06](https://cloud.githubusercontent.com/assets/7251962/6807526/dcc604d6-d246-11e4-8fac-8e1c3b8926e9.png)

**Comment by sumikasan** [comment]
Ideally implementing the same sign-in / registration form that we use for the certificates. Pushed to beta

**Comment by ldodds** [comment]
Can we close this as the tidy up was done and then have a separate issue for reimplementing the sign in forms? Same for the registration one #109.
