### ISSUE TITLE
Improve styling of adding links on question page

### ISSUE THREAD

**Issue by ldodds** [theodi/ODMAT#120]
Improve the styling/interaction of adding a link to the question page, at present its just a couple of text boxes that are side by side.

**Comment by ldodds** [comment]
In the about-page-content branch I've styled the add/remove links to use the default button styles. So this is already improved.

**Comment by digitalWestie** [comment]
I don't think there's an example in the mockups, since the buttons are styled, did you just want the spacing tidied up a bit ?

**Comment by ldodds** [comment]
Yes, if you can tidy up the spacing that would be helpful
