### ISSUE TITLE
Style the assessment page

### ISSUE THREAD

**Issue by ldodds** [theodi/ODMAT#121]
The assessment page is not yet styled/laid out according to the wireframes. The UX needs to be improved and made consistent with the wireframes and other pages.

**Comment by sumikasan** [comment]
http://odmat.herokuapp.com/assessments/13/questions/6
Styling is a bit broken? I am using Chrome

**Comment by digitalWestie** [comment]
Is it that the styles don't match the wireframes or do you think it's something that's not working in chrome?

**Comment by ldodds** [comment]
Actually the issue is covered by #118. Formatting problems are caused by the error message
