### ISSUE TITLE
User cannot edit all answers to a completed activity assessment

### ISSUE THREAD

**Issue by ldodds** [theodi/ODMAT#126]
After completing an activity assessment I can click through to revise my previous answers.

If I've answered No to the first question I can change the answer and proceed through the assessment.

But if I have answered yes to the first question and click "Next Question" to revise the answer to a later question, then instead of seeing the next question I'm taken back to the assessment page -- the application sees the activity assessment as completed so decides I don't need to see any other questions.

**Comment by sumikasan** [comment]
This is still broken.
