### ISSUE TITLE
Tidy up links on assessment pages

### ISSUE THREAD

**Issue by ldodds** [theodi/ODMAT#140]
For the alpha we don't have the "download questions" or "download overview of the questions" content, so can these links be commented out on the assessment page.

I think there's also a similar link when a user starts their first assessment.

We will have links to the grid and guidance though, these can be added in today.

The PDF for the grid is here:

https://drive.google.com/uc?export=download&id=0B4rriq9nxtslOHRQMEhZOFRXSTg

The PDF for guide is here:

https://drive.google.com/uc?export=download&id=0B4rriq9nxtslRUxUalVsbUQ2TkU

**Comment by sumikasan** [comment]
Download White Paper - this should be called:
Download the guide
