### ISSUE TITLE
Fix styling on home page

### ISSUE THREAD

**Issue by ldodds** [theodi/ODMAT#141]
The changes to the assessment styling have affected the styling on the homepage.

See:

http://upcloseandpixelated.com/ODMAT/pages/index.html

But in the app now the "Start Now" and 1/2/3 sections now have black titles, whereas previously they were white. Looks like there were some changes to base.scss which may be the cause.

**Comment by ldodds** [comment]
The button on the /about page is similarly affected, so its probably a default style for headings

**Comment by sumikasan** [comment]
This has not been fixed. It's still black.
