### ISSUE TITLE
User can read help text for all questions

### ISSUE THREAD

**Issue by ldodds** [theodi/ODMAT#15]
Display the notes associated with the question

**Comment by ldodds** [comment]
This blocked by #68

**Comment by ldodds** [comment]
@jenthomson I'm assuming for displaying help text with a question we can use the right hand side of the question box?

E.g. space next to question here: 

https://projects.invisionapp.com/share/6G2FS4IWB#/screens/67620389?maintainScrollPosition=false

**Comment by jenthomson** [comment]
Sure. Do we have any examples of help text that I can use in the mockups?

**Comment by ldodds** [comment]
We don't yet. It'll be a short paragraph of text, perhaps with a link.

On 23 March 2015 at 10:56, Jen <notifications@github.com> wrote:

> Sure. Do we have any examples of help text that I can use in the mockups?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theodi/ODMAT/issues/15#issuecomment-84944967>.
>



-- 
Leigh Dodds, Senior Consultant, theODI.org
@ldodds
The ODI, 65 Clifton Street, London EC2A 4JE

**Comment by sumikasan** [comment]
I am not seeing any help texts
