### ISSUE TITLE
Navigation issue - editing your response from the completed "activity"

### ISSUE THREAD

**Issue by sumikasan** [theodi/ODMAT#152]
1. Go to 'new assessment' dashboard
2. Start the new assessment by clicking 'Begin'- > Data release process
3. Answer 'No' and click 'Next question' to return to the 'new assessment' dashboard
4. Click 'Edit' to change the response from 'No' to 'Yes'

Expectation: go to the next question
What happened: user is taken back to the new assessment dashboard

**Comment by ldodds** [comment]
@rory can you investigate this as a priority? It will block the release.

**Comment by sumikasan** [comment]
It is now working, so I will close this.
