### ISSUE TITLE
Post registration - My assessment page is missing the questions

### ISSUE THREAD

**Issue by sumikasan** [theodi/ODMAT#161]
After registration, user is re-directed to My assessments page (see the screenshot)

The link, download assessment questions, do not work.

![uploads/01ee9e95-45e0-4533-bd9e-7ef0bdc56526/Screen Shot 2015-04-01 at 13.48.14.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F01ee9e95-45e0-4533-bd9e-7ef0bdc56526%2FScreen+Shot+2015-04-01+at+13.48.14.png)

**Comment by sumikasan** [comment]
@ldodds - do you have the full list of assessment questions that can be used? If not, we should take this out, or change this to 'Download assessment grid'?

**Comment by ldodds** [comment]
I'll remove this now. For the beta I suggest we add a page where we list questions for each activity, we can generate them as a web page (might be tricky as a PDF)
