### ISSUE TITLE
Unexpected behaviour when using 'Save and exit'

### ISSUE THREAD

**Issue by sumikasan** [theodi/ODMAT#164]
1. Go to the first Activity question and answer 'yes'
2. Go to the second Activity question, and answer 'yes'
3. Go to the third question, and answer 'no'
4. Hit 'Save and exit'

Expectation: it saves the answer, and mark the activity as complete

What's happening: 
1) Activity is marked as In progress
2) When you click 'In progress' the last question you entered is lost

**Comment by sumikasan** [comment]
The functionality works as expected for the first question, i.e. if you select 'no' and hit 'save and exit' the questions are marked as complete

**Comment by sumikasan** [comment]
Let's discuss how best to approach this for Beta

**Comment by ldodds** [comment]
Closing as same as #211
