### ISSUE TITLE
Page Title includes breadcrumb HTML 

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/ODMAT#171]
![image](https://cloud.githubusercontent.com/assets/9379524/7126711/e91bef8c-e27e-11e4-8209-22efe96ca8e2.jpg)

**Comment by ldodds** [comment]
Closing as duplicate of #157. Thanks for reporting this, and the others though!

**Comment by Stephen-Gates** [comment]
No probs. I'll keep looking as we work our way through the questions.

**Comment by ldodds** [comment]
Really appreciate the testing you're doing. Ping me if you want to to discuss anything that does fit here :)
