### ISSUE TITLE
View goals for next assessment

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/ODMAT#195]
We just had a team meeting to set our goals for the next assessment. After setting the goals and receiving a confirmation message, there didn't seem to be a way to view your goals. I found by chance it in the Activities Tab.  Perhaps some clarity could be added to the Tab names and/or the confirmation message. E.g. Activities could become Your Scores and Goals

**Comment by ldodds** [comment]
We've relabelled all of the tabs and included some additional links on the report page. When the beta is launched in next few days can you take a look?

**Comment by Stephen-Gates** [comment]
Will do. We're keen to see where we land on the heat map and see all the new trinkets you've added.

**Comment by Stephen-Gates** [comment]
@ldodds tabs names are better. Statistics is hidden in footer, I expected to see it as another tab. Thanks for all your hard work getting ODMAT to Beta.
