### ISSUE TITLE
implement questionnaire model

### ISSUE THREAD

**Issue by ldodds** [theodi/ODMAT#38]
## Questionnaire

* id
* version number
* list of questions

## Question

* questionnaire id
* dimension - one of the five different dimensions in the model
* activity - one of the 15 different activities
* the question
* list of answers

## Answer

* question id (which question is it an answer to)
* text of answer (some will be just yes/no, others will be more descriptive)
* scoring -- minimum maturity score if this answer is selected
* list of suggested improvements

**Comment by ldodds** [comment]
I've just noticed that this outline model doesn't include dependencies between questions/answers. This will need to be added.

Some questions will only become active if the user gives a specific answer to a previous question.

For example we might ask: "How widely adopted is your release process?". For this there are likely to be 3 answers: "its not yet used", "its used in some places", "its used across the organisation". 

If the user selects either of the last two answers, then the next question in that section will be displayed. 

I think the simplest option for implementing this is to: 

* specify dependencies between questions
* flag each answer to indicate whether its a "positive or "negative" answer

So, if a question (Q2) has a dependency on another (Q1). Q2 will only be shown if the user selected one of the "positive" answers to Q1.

**Comment by sumikasan** [comment]
@ldodds - has the dependencies between questions/answers have been added, or is this task captured in a separate issue (then is so which one one).
