### ISSUE TITLE
User should be able to revise assessment title and notes

### ISSUE THREAD

**Issue by ldodds** [theodi/ODMAT#94]
see: https://projects.invisionapp.com/share/6G2FS4IWB#/screens/67620385?maintainScrollPosition=false

user should be able to click on assessment title and notes and revise them

**Comment by ldodds** [comment]
@digitalWestie moving this back to in progress as I don't think its done yet?

**Comment by digitalWestie** [comment]
wasn't 100% clear on this one, is the idea that the title and notes can be updated by in-place editing?

**Comment by ldodds** [comment]
Yep, it should be:

* start a new assessment and be prompted for title/description -- think
we've lost this step somewhere so needs adding back in
* when an assessment is in progress, I should be able to edit in place to
revise.

L.

On 30 March 2015 at 11:23, digitalWestie <notifications@github.com> wrote:

> wasn't 100% clear on this one, is the idea that the title and notes can be
> updated by in-place editing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theodi/ODMAT/issues/94#issuecomment-87625049>.
>



-- 
Leigh Dodds, Senior Consultant, theODI.org
@ldodds
The ODI, 65 Clifton Street, London EC2A 4JE
